### ISSUE TITLE
GH action: Debian package is missing Debian revision number

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#31]
Debian package created by GH action is missing Debian revision number.

Wrong: `linz-lds-bde-schema_1.10.1-linz~bionic1_all.deb`
Correct: `linz-lds-bde-schema_1.10.1-1linz~bionic1_all.deb`

**Comment by strk** [comment]
Ok, this is tricky. We're going to create versions like `1.10.1-2-g0000` from commits in the `stable-1.10` branch, so how are we going to control precedence ? Do you see debian changes occurring without commits to the repository ? Because commits in the repository will be already changing version, as well as tags will...

**Comment by strk** [comment]
@imincik I've added the debian revision in PR #30 - please review that one

**Comment by imincik** [comment]
> Do you see debian changes occurring without commits to the repository ?

No, you always commit all changes to repo or I don't understand your question. BTW, `dch` command has `--increment` switch. Can this help ?

**Comment by imincik** [comment]
Ah, I just realized. The problem is that from time to time we discover some issue with packaging and in this case we want to increment only Debian revision value and repackage (without releasing new software version). What we are going to do in this case ?

**Comment by strk** [comment]
How about a DEBIAN_REVISION env variable support in the Docker image ?

**Comment by strk** [comment]
While I was adding a DEBIAN_REVISION I realized what I said is still true. That is: if we find an issue with the debian package, such issue, to be fixed, will need to be addressed by committing a new change to the repository. Doing this, in turn, will result in the `git describe` call to return a value like `1.5.0-1-gxxxx` which will be used for the debian package version, so a concept of "revision" is already in place. Only we cannot have the github-action publish those packages because we'd need a tag to trigger publication. Doing the publication manually would still work fine though.

Or, we can just tag a 1.5.0-1 explicitly and everything should work fine. In both cases I don't see the need for a debian revision at all. Enough that I'd revert 7b752ff8d7f199d6b4fa20760f57df65a8295622 in this PR. If you're ok with this I'd drop that commit, merge and tag a v3 of this repository, then move on to use the new version from packages (including linz-bde-schema for which we need a new tag)

**Comment by strk** [comment]
I'll merge as-is, or can't continue

**Comment by imincik** [comment]
> Or, we can just tag a 1.5.0-1 explicitly and everything should work fine

I don't like idea of tagging `1.5.0-1`

**Comment by imincik** [comment]
I think what we should do is to drop Debian revision completely. `debian_revision` is optional, but as far as I remember, when not specifying it, you have to change package type to Debian `native` which is done in `debian/source/format` file
