### ISSUE TITLE
Patch version number is missing in Ubuntu package file name

### ISSUE THREAD

**Issue by imincik** [linz/linz-software-repository#42]
Patch version number is missing in Ubuntu package file name. For example `https://packagecloud.io/linz/test/packages/ubuntu/bionic/linz-bde-schema_1.12-start-linz~bionic_all.deb`

**Comment by strk** [comment]
That's a tag which should teoretically NOT produce an upload. The problem is that the code that SKIPS the upload will always be committed *after* the tagged commit, which results in such upload. I think we should just manually delete those packages from packagecloud and be done. I'll proceed in this way.

**Comment by strk** [comment]
I see the package was removed, so I'm closing this.
